apiVersion: v1
kind: ReplicationController
metadata:
        name: nsx-demo
        labels:
                app: nsx-demo
spec:
        replicas: 4
        template:
                metadata:
                        labels:
                                app: nsx-demo
                                secgroup: app-tier
                spec:
                        containers:
                                - name: nsx-demo
                                  image: danpaul81/nsx-demo
                                  imagePullPolicy: Always
                                  ports:
                                          - containerPort: 8080

